apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentiment-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: sentiment.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: sentiment-api
            port:
              number: 80

